import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import prettier from 'prettier';

const PUBLIC_DIR = path.resolve('public');
const PUBLIC_IMAGES_DIR = path.join(PUBLIC_DIR, 'images');
const OUTPUT_FILE = path.resolve(
  'packs/ootmm/src/generated/publicImageAssetVersions.ts',
);
const IMAGE_EXTENSIONS = new Set([
  '.avif',
  '.gif',
  '.jpg',
  '.jpeg',
  '.png',
  '.svg',
  '.webp',
]);

async function collectImageFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const paths = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        return collectImageFiles(entryPath);
      }
      if (!entry.isFile()) {
        return [];
      }
      return IMAGE_EXTENSIONS.has(path.extname(entry.name).toLowerCase())
        ? [entryPath]
        : [];
    }),
  );

  return paths.flat();
}

function toPublicPath(filePath: string): string {
  return path.relative(PUBLIC_DIR, filePath).split(path.sep).join('/');
}

async function hashFile(filePath: string): Promise<string> {
  const contents = await readFile(filePath);
  return createHash('sha256').update(contents).digest('hex').slice(0, 12);
}

async function generatePublicImageAssetVersions(): Promise<void> {
  const files = (await collectImageFiles(PUBLIC_IMAGES_DIR)).sort((a, b) =>
    toPublicPath(a).localeCompare(toPublicPath(b)),
  );

  const entries = await Promise.all(
    files.map(async (filePath) => [
      toPublicPath(filePath),
      await hashFile(filePath),
    ]),
  );
  const versions = Object.fromEntries(entries);

  const output = `// AUTO-GENERATED by scripts/generate_public_image_asset_versions.ts
// Do not edit manually.

export const PUBLIC_IMAGE_ASSET_VERSIONS = ${JSON.stringify(versions, null, 2)} as const satisfies Record<string, string>
`;

  const formattedOutput = await prettier.format(output, {
    ...(await prettier.resolveConfig(OUTPUT_FILE)),
    filepath: OUTPUT_FILE,
  });

  await mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
  await writeFile(OUTPUT_FILE, formattedOutput, 'utf8');
  console.log(
    `Generated ${entries.length} public image asset versions -> ${path.relative(
      process.cwd(),
      OUTPUT_FILE,
    )}`,
  );
}

generatePublicImageAssetVersions().catch((error) => {
  console.error('Failed to generate public image asset versions:', error);
  process.exitCode = 1;
});
