import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import prettier from 'prettier';

const ICONS_DIR = path.resolve('public/images/map_icons');
const OUTPUT_FILE = path.resolve('packs/ootmm/src/data/maps/mapIconIndex.ts');

async function generateMapIconIndex(): Promise<void> {
  const entries = await readdir(ICONS_DIR, { withFileTypes: true });
  const iconNames = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.png'))
    .map((entry) => entry.name.replace(/\.png$/i, ''))
    .sort((a, b) => a.localeCompare(b));

  const output = `// AUTO-GENERATED by scripts/generate_map_icon_index.ts
// Do not edit manually.

export const MAP_ICON_INDEX = ${JSON.stringify(iconNames, null, 2)} as const
`;

  const formattedOutput = await prettier.format(output, {
    ...(await prettier.resolveConfig(OUTPUT_FILE)),
    filepath: OUTPUT_FILE,
  });

  await writeFile(OUTPUT_FILE, formattedOutput, 'utf8');
  console.log(
    `Generated ${iconNames.length} map icons -> ${path.relative(process.cwd(), OUTPUT_FILE)}`,
  );
}

generateMapIconIndex().catch((error) => {
  console.error('Failed to generate map icon index:', error);
  process.exitCode = 1;
});
