#!/usr/bin/env python3
from __future__ import annotations

import ast
import json
import re
import shutil
import subprocess
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GI_PATH = ROOT / 'OoTMM' / 'data' / 'defs' / 'gi.yml'
NAMES_PATH = ROOT / 'OoTMM' / 'packages' / 'generator' / 'lib' / 'combo' / 'names.ts'
ITEMS_PATH = ROOT / 'packs' / 'ootmm' / 'src' / 'data' / 'items.ts'
GI_ITEMS_TS = ROOT / 'packs' / 'ootmm' / 'src' / 'data' / 'giItems.ts'
ITEMS_AUTOGEN_HEADER = '// AUTO-GENERATED by scripts/sync_gi_items.py'
ITEM_DATABASE_MARKER = 'export const ITEM_DATABASE: OoTMMItem[] = ['

PREFIXES_TO_STRIP = (
    'the ',
    'a ',
    'an ',
    'some ',
)

NAME_PATTERN = re.compile(
    r'^\s*([A-Z0-9_]+)\s*:\s*("([^"\\]|\\.)*"|\'([^\'\\]|\\.)*\')\s*,?\s*$'
)

DYNAMIC_MAX_COUNT_ITEMS = {
    'MM_CLOCK',
    'MM_OCARINA',
    'MM_SCALE',
    'MM_SHIELD',
    'MM_SWORD',
    'MM_STRENGTH',
    'MM_WALLET',
    'OOT_HOOKSHOT',
    'OOT_OCARINA',
    'OOT_SCALE',
    'OOT_SHIELD',
    'OOT_SWORD',
    'OOT_SWORD_GORON',
    'OOT_STRENGTH',
    'OOT_WALLET',
    'SHARED_HOOKSHOT',
    'SHARED_OCARINA',
    'SHARED_SCALE',
    'SHARED_SHIELD',
    'SHARED_SWORD',
    'SHARED_STRENGTH',
    'SHARED_WALLET',
}


def clean_name(raw: str) -> str:
    name = re.sub(r'<[^>]+>', '', raw)
    name = re.sub(r'\s+', ' ', name).strip()
    lowered = name.lower()
    for prefix in PREFIXES_TO_STRIP:
        if lowered.startswith(prefix):
            name = name[len(prefix):].strip()
            lowered = name.lower()
            break
    if name and name[0].islower():
        name = name[0].upper() + name[1:]
    return name


def fallback_name(item_id: str) -> str:
    name = re.sub(r'^(OOT_|MM_|SHARED_)', '', item_id)
    parts = name.split('_')
    return ' '.join([p[:1].upper() + p[1:].lower() if p else '' for p in parts]).strip()


def parse_gi_items() -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    seen: set[str] = set()
    for line in GI_PATH.read_text().splitlines():
        m = re.search(r'\bid:\s*([^,}]+)', line)
        if not m:
            continue
        item_id = m.group(1).strip()
        if item_id in seen:
            continue
        seen.add(item_id)
        m_name = re.search(r'\bname:\s*\"([^\"]*)\"', line)
        if m_name:
            name = clean_name(m_name.group(1))
        else:
            name = fallback_name(item_id)
        items.append({'id': item_id, 'name': name})
    return items


def parse_core_names() -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    seen: set[str] = set()
    for line in NAMES_PATH.read_text().splitlines():
        m = NAME_PATTERN.match(line)
        if not m:
            continue
        item_id = m.group(1)
        if item_id in seen:
            continue
        raw_literal = m.group(2)
        try:
            name = ast.literal_eval(raw_literal)
        except Exception:
            name = raw_literal.strip('\'"')
        items.append({'id': item_id, 'name': name})
        seen.add(item_id)
    return items


def find_matching_bracket(source: str, opening_index: int) -> int:
    depth = 0
    i = opening_index
    state = 'code'
    string_quote = ''

    while i < len(source):
        ch = source[i]
        nxt = source[i + 1] if i + 1 < len(source) else ''

        if state == 'code':
            if ch == '/' and nxt == '/':
                state = 'line_comment'
                i += 2
                continue
            if ch == '/' and nxt == '*':
                state = 'block_comment'
                i += 2
                continue
            if ch in ("'", '"', '`'):
                state = 'string'
                string_quote = ch
                i += 1
                continue
            if ch == '[':
                depth += 1
                i += 1
                continue
            if ch == ']':
                depth -= 1
                if depth == 0:
                    return i
                i += 1
                continue
            i += 1
            continue

        if state == 'line_comment':
            if ch == '\n':
                state = 'code'
            i += 1
            continue

        if state == 'block_comment':
            if ch == '*' and nxt == '/':
                state = 'code'
                i += 2
                continue
            i += 1
            continue

        if state == 'string':
            if ch == '\\':
                i += 2
                continue
            if ch == string_quote:
                state = 'code'
            i += 1
            continue

    raise ValueError('Could not find matching closing bracket for ITEM_DATABASE array.')


def parse_item_database_sections(source: str) -> tuple[str, str, str]:
    marker_index = source.find(ITEM_DATABASE_MARKER)
    if marker_index < 0:
        raise ValueError(f'Could not find marker: {ITEM_DATABASE_MARKER}')

    open_index = marker_index + len(ITEM_DATABASE_MARKER) - 1
    close_index = find_matching_bracket(source, open_index)
    prefix = source[: open_index + 1]
    body = source[open_index + 1 : close_index]
    suffix = source[close_index:]
    return prefix, body, suffix


def parse_existing_item_entries(items_array_body: str) -> tuple[dict[str, str], list[str]]:
    entries_by_id: dict[str, str] = {}
    order: list[str] = []
    depth = 0
    i = 0
    start = -1
    state = 'code'
    string_quote = ''

    while i < len(items_array_body):
        ch = items_array_body[i]
        nxt = items_array_body[i + 1] if i + 1 < len(items_array_body) else ''

        if state == 'code':
            if ch == '/' and nxt == '/':
                state = 'line_comment'
                i += 2
                continue
            if ch == '/' and nxt == '*':
                state = 'block_comment'
                i += 2
                continue
            if ch in ("'", '"', '`'):
                state = 'string'
                string_quote = ch
                i += 1
                continue
            if ch == '{':
                if depth == 0:
                    start = i
                depth += 1
                i += 1
                continue
            if ch == '}':
                depth -= 1
                if depth == 0 and start >= 0:
                    snippet = items_array_body[start : i + 1]
                    normalized = textwrap.dedent(snippet).strip()
                    id_match = re.search(r'\bid:\s*[\'"]([^\'"]+)[\'"]', normalized)
                    if id_match:
                        item_id = id_match.group(1)
                        if item_id not in entries_by_id:
                            entries_by_id[item_id] = normalized
                            order.append(item_id)
                    start = -1
                i += 1
                continue
            i += 1
            continue

        if state == 'line_comment':
            if ch == '\n':
                state = 'code'
            i += 1
            continue

        if state == 'block_comment':
            if ch == '*' and nxt == '/':
                state = 'code'
                i += 2
                continue
            i += 1
            continue

        if state == 'string':
            if ch == '\\':
                i += 2
                continue
            if ch == string_quote:
                state = 'code'
            i += 1
            continue

    return entries_by_id, order


def get_category(item_id: str) -> str:
    if 'KEY' in item_id:
        return 'key'
    if 'SONG' in item_id:
        return 'song'
    if 'MASK' in item_id:
        return 'mask'
    if any(token in item_id for token in ('SWORD', 'SHIELD', 'TUNIC', 'BOOTS')):
        return 'equipment'
    if any(token in item_id for token in ('BOW', 'HOOKSHOT', 'HAMMER', 'OCARINA', 'LENS')):
        return 'equipment'
    if any(token in item_id for token in ('SCALE', 'STRENGTH', 'WALLET', 'MAGIC')):
        return 'equipment'
    if any(token in item_id for token in ('MEDALLION', 'STONE', 'REMAINS')):
        return 'quest'
    if 'TRAP' in item_id:
        return 'trap'
    if 'MAP' in item_id or 'COMPASS' in item_id:
        return 'dungeon'
    if 'STRAY_FAIRY' in item_id:
        return 'dungeon'
    if 'GS_TOKEN' in item_id:
        return 'token'
    if 'SOUL' in item_id:
        return 'soul'
    if 'RUPEE' in item_id:
        return 'consumable'
    return 'misc'


def get_game(item_id: str) -> str:
    if item_id.startswith('MM_'):
        return 'mm'
    if item_id.startswith('OOT_'):
        return 'oot'
    return 'shared'


def get_icon(item_id: str, category: str) -> str:
    icon = '❓'
    if category == 'key':
        icon = '🔑'
    if 'BOSS_KEY' in item_id:
        icon = '🗝️'
    if category == 'song':
        icon = '🎵'
    if category == 'mask':
        icon = '🎭'
    if 'SWORD' in item_id:
        icon = '⚔️'
    if 'SHIELD' in item_id:
        icon = '🛡️'
    if 'BOW' in item_id:
        icon = '🏹'
    if 'BOMB' in item_id:
        icon = '💣'
    if 'POTION' in item_id:
        icon = '🧪'
    if 'BOTTLE' in item_id:
        icon = '🍾'
    if 'MAP' in item_id:
        icon = 'Map'
    if 'COMPASS' in item_id:
        icon = 'Comp'
    if 'GS_TOKEN' in item_id:
        icon = '💀'
    if 'HEART' in item_id:
        icon = '❤️'
    if 'MEDALLION' in item_id:
        icon = '🏅'
    if 'STONE' in item_id:
        icon = '💎'
    if 'REMAINS' in item_id:
        icon = '👹'
    if 'TRAP' in item_id:
        icon = '⚠️'
    if 'SOUL' in item_id:
        icon = '👻'
    return icon


def get_max_count(item_id: str) -> int | None:
    if item_id == 'OOT_GS_TOKEN':
        return 100
    if item_id.startswith('MM_GS_TOKEN_'):
        return 30
    if 'STRAY_FAIRY' in item_id:
        return 15
    if 'RUPEE_SILVER' in item_id:
        return 5
    return None


def write_gi_items_ts(gi_items: list[dict[str, str]]):
    lines = []
    lines.append('// Auto-generated from OoTMM/data/defs/gi.yml')
    lines.append('// and OoTMM/packages/generator/lib/combo/names.ts')
    lines.append('export const GI_ITEM_LIST = [')
    for item in gi_items:
        name_literal = json.dumps(item['name'], ensure_ascii=False)
        lines.append(f"  {{ id: '{item['id']}', name: {name_literal} }},")
    lines.append('] as const')
    lines.append('')
    GI_ITEMS_TS.write_text('\n'.join(lines) + '\n')


def ensure_items_autogen_header(source: str) -> str:
    lines = source.splitlines()
    while lines and lines[0].startswith(ITEMS_AUTOGEN_HEADER):
        lines = lines[1:]
    body = '\n'.join(lines).lstrip('\n')
    return f'{ITEMS_AUTOGEN_HEADER}\n{body}' if body else f'{ITEMS_AUTOGEN_HEADER}\n'


def render_new_item_entry(item_id: str, name: str) -> str:
    category = get_category(item_id)
    game = get_game(item_id)
    if 'SOUL' in item_id:
        category = 'soul'
    if 'TRAP' in item_id:
        category = 'trap'
    icon = get_icon(item_id, category)

    max_count = get_max_count(item_id)
    if item_id in DYNAMIC_MAX_COUNT_ITEMS:
        max_count = None

    parts = [
        f"id: '{item_id}'",
        f'name: {json.dumps(name, ensure_ascii=False)}',
        f"category: '{category}'",
        f"game: '{game}'",
        f'icon: {json.dumps(icon, ensure_ascii=False)}',
    ]
    if max_count is not None:
        parts.append(f'maxCount: {max_count}')
    return '{ ' + ', '.join(parts) + ' }'


def write_items_ts(gi_items: list[dict[str, str]]) -> tuple[list[str], list[str]]:
    source = ensure_items_autogen_header(ITEMS_PATH.read_text())
    prefix, existing_body, suffix = parse_item_database_sections(source)
    existing_entries, existing_order = parse_existing_item_entries(existing_body)

    gi_ids = [item['id'] for item in gi_items]
    gi_name_map = {item['id']: item['name'] for item in gi_items}
    gi_set = set(gi_ids)

    kept_ids = [item_id for item_id in existing_order if item_id in gi_set]
    removed_ids = [item_id for item_id in existing_order if item_id not in gi_set]
    existing_set = set(existing_order)

    added_ids: list[str] = []
    for item_id in gi_ids:
        if item_id in existing_set:
            continue
        kept_ids.append(item_id)
        added_ids.append(item_id)

    rendered_entries: list[str] = []
    for item_id in kept_ids:
        existing_entry = existing_entries.get(item_id)
        if existing_entry is not None:
            rendered_entries.append(textwrap.indent(existing_entry, '  '))
            continue
        name = gi_name_map.get(item_id, fallback_name(item_id))
        rendered_entries.append(textwrap.indent(render_new_item_entry(item_id, name), '  '))

    if rendered_entries:
        new_body = '\n' + ',\n'.join(rendered_entries) + '\n'
    else:
        new_body = '\n'

    ITEMS_PATH.write_text(prefix + new_body + suffix)
    return added_ids, removed_ids


def run_prettier(paths: list[Path]) -> bool:
    str_paths = [str(path) for path in paths]
    commands: list[list[str]] = []

    local_prettier = ROOT / 'node_modules' / '.bin' / 'prettier'
    if local_prettier.exists():
        commands.append([str(local_prettier), '--write', *str_paths])
    if shutil.which('prettier'):
        commands.append(['prettier', '--write', *str_paths])
    if shutil.which('npx'):
        commands.append(['npx', 'prettier', '--write', *str_paths])
    if shutil.which('pnpm'):
        commands.append(['pnpm', 'prettier', '--', '--write', *str_paths])

    seen: set[tuple[str, ...]] = set()
    for cmd in commands:
        key = tuple(cmd)
        if key in seen:
            continue
        seen.add(key)
        try:
            subprocess.run(cmd, check=True)
            return True
        except Exception:
            continue

    return False


def main():
    gi_items = parse_gi_items()
    core_items = parse_core_names()
    gi_ids = {item['id'] for item in gi_items}
    for item in core_items:
        if item['id'] in gi_ids:
            continue
        gi_items.append(item)
    write_gi_items_ts(gi_items)
    added_ids, removed_ids = write_items_ts(gi_items)
    if run_prettier([GI_ITEMS_TS, ITEMS_PATH]):
        print(f"Formatted with Prettier: {GI_ITEMS_TS}, {ITEMS_PATH}")
    else:
        print('Could not run Prettier (not installed or execution failed).')
    print(f"Wrote {GI_ITEMS_TS}")
    print(f"Wrote {ITEMS_PATH}")
    print(f'ITEM_DATABASE: +{len(added_ids)} / -{len(removed_ids)}')


if __name__ == '__main__':
    main()
